### ISSUE TITLE
Current day selection is not updated

### ISSUE THREAD

**Issue by Djaler** [elementary/wingpanel-indicator-datetime#93] opened 2018-08-27 19:16 UTC
![image](https://user-images.githubusercontent.com/7964583/44680598-d901b300-aa46-11e8-817f-ff37a3a8fe35.png)

**Comment by jlnr** [comment] 2018-09-06 11:59
Duplicate of #4?

**Comment by cassidyjames** [comment] 2018-10-09 19:53
@jlnr ah yeah it looks like it.

**Closed by cassidyjames** 2018-10-09 19:53 UTC
Labels: Priority: High, Status: Confirmed
