### ISSUE TITLE
Wingpanel Crashes when clicking on the date - Google Calendar

### ISSUE THREAD

**Issue by b3n10** [elementary/wingpanel-indicator-datetime#58] opened 2018-02-22 23:06 UTC
There is an existing same [issue](https://github.com/elementary/wingpanel-indicator-datetime/issues/11) specifically for calDav, but i'm using Google Calendar. If I will remove my google account, then clicking datetime indicator will not crash wingpanel and dropdown shows fine. 

I followed steps [suggested here](https://bugs.launchpad.net/wingpanel-indicator-datetime/+bug/1635766/comments/2) to run `gdb wingpanel` and here is the result:

- [pastebin](https://pastebin.com/raw/qGU1BgY6)
- Timezone: GMT+/--8:00 (Manila, Philippines)
- Locale: EN-US
- elementary OS 0.4.1 Loki

**Comment by tintou** [comment] 2018-12-12 09:19
Indeed a duplicate of #11

**Closed by tintou** 2018-12-12 09:19 UTC
