### ISSUE TITLE
Wingpanel calander glitches after attempted CANVAS calander import

### ISSUE THREAD

**Issue by CodeManS99** [elementary/wingpanel-indicator-datetime#111] opened 2018-02-13 08:03 UTC
After I imported a calendar from my college CANVAS calendar page, I noticed that the import only added about half of the events. After this, I tried to view the calendar from the wingpanel and discovered that something that I did broke that. Attached is a video of what happens when I click on the wingpanel calendar.
[Calendar error.mp4.gz](https://github.com/elementary/calendar/files/1719110/Calendar.error.mp4.gz)

**Comment by peteruithoven** [comment] 2018-12-12 01:06
Might be related to: https://github.com/elementary/wingpanel-indicator-datetime/issues/11

**Comment by tintou** [comment] 2018-12-12 09:16
Yes, it's a duplicate of #11

**Closed by tintou** 2018-12-12 09:16 UTC
