### ISSUE TITLE
The clock is missing from the panel

### ISSUE THREAD

**Issue by AustrianLinuxMemer** [elementary/wingpanel-indicator-datetime#318] opened 2024-11-06 14:53 UTC
### What Happened?

The clock is missing from the panel

![panel](https://github.com/user-attachments/assets/2011e278-6668-4536-9069-95fc01949106)

### Steps to Reproduce

Installing the current release candidate of ElementaryOS.
Even resetting the settings to their original state doesn't do anything

### Expected Behavior

The clock should be there

### OS Version

7.x (Horus)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment] 2024-11-06 15:05
First, could you check the result of the following command to check if the package to show the clock in the panel is installed?

```
$ LANG=C apt-cache policy wingpanel-indicator-datetime
```

**Comment by AustrianLinuxMemer** [comment] 2024-11-07 08:11
Result of `LANG=C apt-cache policy wingpanel-indicator-datetime`:

```
wingpanel-indicator-datetime:
  Installed: (none)
  Candidate: 2.4.2+r1007+pkg34~ubuntu22.04.1
  Version table:
     2.4.2+r1007+pkg34~ubuntu22.04.1 500
        500 https://ppa.launchpadcontent.net/elementary-os/stable/ubuntu jammy/main amd64 Packages
```

**Comment by AustrianLinuxMemer** [comment] 2024-11-07 08:18
Fixed it on my system by installing `wingpanel-indicatot-datetime` on my system. I don't know why the clock disappeared at one time though

**Comment by ryonakano** [comment] 2024-11-07 14:04
So the cause of your issue was that `wingpanel-indicator-datetime` is not installed. It should be installed by default on elementary OS so I'm not sure why it's not on your system. I tried installing elementary OS 7.1 and updating to latest packages just now, but `wingpanel-indicator-datetime` is not removed and the clock is there.

Closing as resolved.

**Closed by ryonakano** 2024-11-07 14:04 UTC
