### ISSUE TITLE
No event dots since added libecal-2.0 support

### ISSUE THREAD

**Issue by worldofpeace** [elementary/wingpanel-indicator-datetime#206] opened 2020-03-28 23:02 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I add some events to my calendar on the same day and wingpanel-indicator-datetime doesn't show any dots counting those events.

### To Reproduce
1. Build wingpanel-indicator-datetime with libecal-2.0
2. Add events with elementary-calendar
3. Open wingpanel-indicator-datetime and navigate to that day
4. See no dots on date

### Expected behavior

I would see some pretty dots

### Screenshots or screen recordings
![Screenshot from 2020-03-28 18 57 57](https://user-images.githubusercontent.com/28888242/77835740-1c8e3880-7126-11ea-88f4-9603335be962.png)

### Logs
Running wingpanel with `G_MESSAGES_DEBUG=all` yielded no errors when selecting wingpanel-indicator-datetime.

## Platform Information

- OS: NixOS
- OS Version: 20.09 git
This is using a GNOME 3.34 stack. (not for long though, will see if I can still reproduce when that upgrade is merged).

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by J0Ar** [comment] 2020-04-04 10:42
Event dots are also gone on elementaryOS. 🤷‍♂️️

**Comment by worldofpeace** [comment] 2020-04-04 19:14
@J0Ar Very strange. Could you query with dpkg (or apt, can't remember) what version of evolution-data-server is at?

**Comment by J0Ar** [comment] 2020-04-04 20:00
@worldofpeace I tried an older installation of elementaryOS, where the indicator was at version `2.2.1+r555+pkg22~ubuntu5.1.1` and there the event dots are still working.
 
But after the upgrade to `2.2.2+r580+pkg23~ubuntu5.1.2.1` and a logout > login the dots are gone.

The **evolution-data-server** was always at…
```
apt-cache show evolution-data-server
Package: evolution-data-server
Architecture: amd64
Version: 3.28.5-0ubuntu0.18.04.2
```

**Comment by worldofpeace** [comment] 2020-04-04 21:18
@J0Ar The only change, which isn't in the release notes, is https://github.com/elementary/wingpanel-indicator-datetime/commit/3ccd05d611e6dd5274a03f061ba1b5e13d6fe0cf.
That allows it to build with latest libecal. What likely happened here (a guess), is the code path that is for the event dots is broken in a libecal-2.0 version, and maybe the conditional compilation isn't right and that code is used for 3.28 as well.

**Comment by worldofpeace** [comment] 2020-04-04 21:21
I've changed the issue that it isn't a regression just for libecal-2.0 users.

**Comment by J0Ar** [comment] 2020-04-05 13:34
I saw this change too but I'm not a developer...my knowledge is only based on user-level. 😬
So, maybe @tintou c/should take a look at this? 🤔🧐🤷🏻‍♂️

**Comment by Dirli** [comment] 2020-04-13 19:45
https://github.com/Dirli/wingpanel-indicator-datetime/tree/refactoring
If someone tests it, it will be great. I don't use this functionality (and there are no events, respectively), but it seems to have been fixed

**Comment by worldofpeace** [comment] 2020-04-13 22:28
> https://github.com/Dirli/wingpanel-indicator-datetime/tree/refactoring
> If someone tests it, it will be great. I don't use this functionality (and there are no events, respectively), but it seems to have been fixed

I can QA this for you.

**Comment by worldofpeace** [comment] 2020-04-13 22:34
@Dirli Yeah, that functionality has returned.
Could you PR part of that branch to fix this bug?

**Comment by Dirli** [comment] 2020-04-15 17:13
> @Dirli Yeah, that functionality has returned.
> Could you PR part of that branch to fix this bug?

No problem, I will try to make a PR within a couple of days

**Comment by JackFrostTheGuardian** [comment] 2020-04-22 15:14
This is not really a major issue but I'd like to have the dots back in wingpanel, it eliminates the purpose of having datetime indicator on wingpanel. Is this going to get fixed? How can I help?

**Comment by worldofpeace** [comment] 2020-04-22 15:59
> This is not really a major issue but I'd like to have the dots back in wingpanel, it eliminates the purpose of having datetime indicator on wingpanel. Is this going to get fixed? How can I help?

@Dirli Has a fix and we're just waiting for it to be PR'd

**Comment by Dirli** [comment] 2020-04-22 16:05
my fix was rejected. fixed too much)

**Comment by JackFrostTheGuardian** [comment] 2020-04-22 16:16
@Dirli I noticed that and while I'm using your fix right now it's concerning how the elementary team is going to fix this if they rejected your PR which is working great by the way. Also if elementary team fix this in future is it possible that the update will take care of it automatically or do I have to manually install it now that I am using your fix? I'm asking this because your fix is versioned 2.2.3 which is probably going to be elementary team's next version also, so will this cause any conflict?

**Comment by Dirli** [comment] 2020-04-22 16:19
@worldofpeace If it were possible not to rewrite it, I wouldn't. But why should I suffer correcting mistakes? I made it as easy as I could (it was easier to rewrite). I haven't added or removed anything new, just refactoring. After that all the fixes are very simple) But they didn't have the time or desire to look at my code (it's really simple there).

**Comment by Dirli** [comment] 2020-04-22 16:29
@JackFrostTheGuardian I was forced to make a package in my repository (for gentoo), because I need all the functionality that I added there) if the developers release a new release, it will just erase my version on the EOS. As for other distributions, I don't know)

**Comment by worldofpeace** [comment] 2020-04-22 16:59
@Dirli Right, I just looked through your diff and you simply cannot pick that apart, it needed a rewrite. I see the only issue they had was conditional compilation of EDS, which I can understand because they have on use for it. For what it's worth, I'm going to use the patchset downstream in NixOS because there's too many issues for me to consider it ship-able ATM.
Thanks @Dirli

**Comment by alainm23** [comment] 2020-04-22 17:05
Hello @Dirli I am the developer [Planner](https://github.com/alainm23/planner), I am having some problems showing calendar events in other distributions like Ubuntu, Pop! OS, etc. My code is based on the wingpanel-indicator-datetime, you think the problem is related to this issue.

https://github.com/alainm23/planner/issues/139

**Comment by ikarosdev** [comment] 2020-05-17 20:09
I think I found the fix for this. During this commit: https://github.com/elementary/wingpanel-indicator-datetime/commit/3ccd05d611e6dd5274a03f061ba1b5e13d6fe0cf

I think this line was accidentally removed from CalendarModel.vala:

`events_added (source, added_events.read_only_view);`

Re-adding this line fixes the issue for me.

**Comment by ryonakano** [comment] 2020-05-17 21:06
@ikarosdev Would you made a PR?

**Comment by ikarosdev** [comment] 2020-05-17 21:59
Thanks @danrabbit. I should've made a PR for this.

**Comment by danrabbit** [comment] 2020-05-17 22:00
Thank you for finding the source of the issue! Happy to turn it into a PR

**Closed** 2020-05-17 22:01 UTC
Labels: Status: In Progress
