### ISSUE TITLE
Highlighted "Today's date" button missing border on the left

### ISSUE THREAD

**Issue by D0J0P** [elementary/wingpanel-indicator-datetime#277] opened 2021-10-15 04:53 UTC
### What Happened?

Some or all of the border on the left of the button of "Today's date" is missing in it's clicked state.

### Steps to Reproduce

1. Open wingpanel-datetime
2. Click "Today's date"
3. look at the accent color border, and see how the left side is missing. I'm on dark mode, so it might be more noticeable there. In fact, it looks normal on default mode.
![Screenshot from 2021-10-15 00-47-44](https://user-images.githubusercontent.com/19495660/137434261-19a1c058-0b71-46aa-bc49-75da06ba0c8c.png)

### Expected Behavior

That the border would be even on all sides, since it's a middle button. 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment] 2021-10-15 16:36
Hey thanks for reporting this issue! This is actually a duplicate of https://github.com/elementary/stylesheet/issues/904

Closing as duplicate

**Closed as completed by danrabbit** 2021-10-15 16:36 UTC
Labels: Status: Duplicate
