### ISSUE TITLE
Add a "world clock" widget next to the calendar

### ISSUE THREAD

**Issue by terndrup** [elementary/wingpanel-indicator-datetime#115] opened 2019-02-24 21:11 UTC
Kinda related to #5 , but I would love to see the ability to add "World clocks" which are shown next to the calendar when you pop up the wingpanel calendar. This is similar to how world clocks are displayed in GNOME. If there are no world clocks defined, the extension can be hidden.

Just an idea!

**Comment by danrabbit** [comment] 2019-07-17 18:04
I'm going to close this as a duplicate of #5 since this sounds like the same feature request

**Closed by danrabbit** 2019-07-17 18:04 UTC
