### ISSUE TITLE
Dates Invisible in Datetime Dropdown 

### ISSUE THREAD

**Issue by rainer2208** [elementary/wingpanel-indicator-datetime#304] opened 2022-10-04 14:44 UTC
### What Happened?

I installed the desktop on Arch Linux couple days ago. 

It is very pleasant and user friendly and I love working with it. 

There is just one thing not working : the datetime dropdown field doesn't show the dates, just an almost empty field with the weekday headers, but no numbers for the dates. 

The fields are clickable, but the date-text is not visible. 
![Date_Time](https://user-images.githubusercontent.com/23400899/193849473-1e3725f9-f9e0-4dac-b2b5-5002a48c13ba.png)

### Steps to Reproduce

Installation website tutorial https://www.addictivetips.com/ubuntu-linux-tips/elementary-os-desktop-arch-linux/ 

### Expected Behavior

Show date and time 

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Hardware Info

Asus VivoBook 
Intel I 5

**Comment by milouse** [comment] 2022-10-10 07:04
I can confirm the problem on archlinux.

I wonder if it’s not a problem introduced by a recent and incompatible version of gtk-3 or gtk-4 ? It looks like a broken theme css rule…

**Comment by davidmhewitt** [comment] 2022-10-10 10:13
I imagine that this is related to this:
https://github.com/elementary/wingpanel-indicator-datetime/issues/303

**Comment by milouse** [comment] 2022-10-11 20:34
I confirm it’s the same as #303 and than #305 fixed perfectly this problem on archlinux too :)

Thus @danirabbit you can also close this ticket as well :)

**Closed** 2022-10-11 20:38 UTC
