### ISSUE TITLE
Weird behavior when switching between months

### ISSUE THREAD

**Issue by donaldp** [elementary/wingpanel-indicator-datetime#289] opened 2021-11-22 07:49 UTC
### What Happened?

Wingpanel calendar always going 1 month back when clicking on the buttons next to the Month, Year.
The button in between the Previous and Next buttons doesn't seem to work either.

Here is the bug in action:
![wingpanel-calendar](https://user-images.githubusercontent.com/6256291/142822228-72fd84d9-8b2c-4642-abee-eb511cb67c04.gif)

### Steps to Reproduce

1. Open the calendar by clicking on the datetime indicator.
2. Click any of the 3 buttons next to the Month and Year.

### Expected Behavior

Switching between months should be consistent between the 2 buttons.
The previous button should go 1 month back when clicking on it and the next button should go 1 month forward when clicking on it.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           61
Model name:                      Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
Stepping:                        4
CPU MHz:                         2394.412
CPU max MHz:                     3000.0000
CPU min MHz:                     500.0000
BogoMIPS:                        4788.82
Virtualization:                  VT-x
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        512 KiB
L3 cache:                        4 MiB
NUMA node0 CPU(s):               0-3
```

**Comment by meisenzahl** [comment] 2021-11-22 13:34
@donaldp could you please clarify if you have the same behavior as described in https://github.com/elementary/wingpanel-indicator-datetime/issues/283.

**Comment by donaldp** [comment] 2021-11-22 14:36
HI @meisenzahl thanks for the reply.
I can confirm that my issue is very similar to the one you have linked in the comment above. Its not exactly the same but it is very similar.
For example: In addition to the issues I've mentioned, whenever I open the calendar, it always goes to October regardless of the current month being November.

**Comment by JoseExposito** [comment] 2021-11-24 07:37
Hi! I'm also affected by this bug. After compiling and installing the latest code, the issue is fixed. It looks like the problem was fixed by https://github.com/elementary/wingpanel-indicator-datetime/pull/284.

@donaldp if you don't mind, I am going to close the issue. Feel free to reopen it if the bug is still present in the next release for you.

**Closed by JoseExposito** 2021-11-24 07:37 UTC
Labels: Status: Confirmed
